# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mion/s/243/jkokoszk/c++/proe_zadanie_programistyczne_nr_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mion/s/243/jkokoszk/c++/proe_zadanie_programistyczne_nr_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mion/s/243/jkokoszk/c++/proe_zadanie_programistyczne_nr_1/CMakeFiles /home/mion/s/243/jkokoszk/c++/proe_zadanie_programistyczne_nr_1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mion/s/243/jkokoszk/c++/proe_zadanie_programistyczne_nr_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named obj

# Build rule for target.
obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj
.PHONY : obj

# fast build rule for target.
obj/fast:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/build
.PHONY : obj/fast

#=============================================================================
# Target rules for targets named program.out

# Build rule for target.
program.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 program.out
.PHONY : program.out

# fast build rule for target.
program.out/fast:
	$(MAKE) -f CMakeFiles/program.out.dir/build.make CMakeFiles/program.out.dir/build
.PHONY : program.out/fast

src/jacket.o: src/jacket.cpp.o

.PHONY : src/jacket.o

# target to build an object file
src/jacket.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/jacket.cpp.o
.PHONY : src/jacket.cpp.o

src/jacket.i: src/jacket.cpp.i

.PHONY : src/jacket.i

# target to preprocess a source file
src/jacket.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/jacket.cpp.i
.PHONY : src/jacket.cpp.i

src/jacket.s: src/jacket.cpp.s

.PHONY : src/jacket.s

# target to generate assembly for a file
src/jacket.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/jacket.cpp.s
.PHONY : src/jacket.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu.o: src/menu.cpp.o

.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/product.o: src/product.cpp.o

.PHONY : src/product.o

# target to build an object file
src/product.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/product.cpp.o
.PHONY : src/product.cpp.o

src/product.i: src/product.cpp.i

.PHONY : src/product.i

# target to preprocess a source file
src/product.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/product.cpp.i
.PHONY : src/product.cpp.i

src/product.s: src/product.cpp.s

.PHONY : src/product.s

# target to generate assembly for a file
src/product.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/product.cpp.s
.PHONY : src/product.cpp.s

src/shoes.o: src/shoes.cpp.o

.PHONY : src/shoes.o

# target to build an object file
src/shoes.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shoes.cpp.o
.PHONY : src/shoes.cpp.o

src/shoes.i: src/shoes.cpp.i

.PHONY : src/shoes.i

# target to preprocess a source file
src/shoes.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shoes.cpp.i
.PHONY : src/shoes.cpp.i

src/shoes.s: src/shoes.cpp.s

.PHONY : src/shoes.s

# target to generate assembly for a file
src/shoes.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shoes.cpp.s
.PHONY : src/shoes.cpp.s

src/shop.o: src/shop.cpp.o

.PHONY : src/shop.o

# target to build an object file
src/shop.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shop.cpp.o
.PHONY : src/shop.cpp.o

src/shop.i: src/shop.cpp.i

.PHONY : src/shop.i

# target to preprocess a source file
src/shop.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shop.cpp.i
.PHONY : src/shop.cpp.i

src/shop.s: src/shop.cpp.s

.PHONY : src/shop.s

# target to generate assembly for a file
src/shop.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shop.cpp.s
.PHONY : src/shop.cpp.s

src/tshirt.o: src/tshirt.cpp.o

.PHONY : src/tshirt.o

# target to build an object file
src/tshirt.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/tshirt.cpp.o
.PHONY : src/tshirt.cpp.o

src/tshirt.i: src/tshirt.cpp.i

.PHONY : src/tshirt.i

# target to preprocess a source file
src/tshirt.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/tshirt.cpp.i
.PHONY : src/tshirt.cpp.i

src/tshirt.s: src/tshirt.cpp.s

.PHONY : src/tshirt.s

# target to generate assembly for a file
src/tshirt.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/tshirt.cpp.s
.PHONY : src/tshirt.cpp.s

src/underwear.o: src/underwear.cpp.o

.PHONY : src/underwear.o

# target to build an object file
src/underwear.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/underwear.cpp.o
.PHONY : src/underwear.cpp.o

src/underwear.i: src/underwear.cpp.i

.PHONY : src/underwear.i

# target to preprocess a source file
src/underwear.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/underwear.cpp.i
.PHONY : src/underwear.cpp.i

src/underwear.s: src/underwear.cpp.s

.PHONY : src/underwear.s

# target to generate assembly for a file
src/underwear.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/underwear.cpp.s
.PHONY : src/underwear.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... obj"
	@echo "... rebuild_cache"
	@echo "... program.out"
	@echo "... src/jacket.o"
	@echo "... src/jacket.i"
	@echo "... src/jacket.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/product.o"
	@echo "... src/product.i"
	@echo "... src/product.s"
	@echo "... src/shoes.o"
	@echo "... src/shoes.i"
	@echo "... src/shoes.s"
	@echo "... src/shop.o"
	@echo "... src/shop.i"
	@echo "... src/shop.s"
	@echo "... src/tshirt.o"
	@echo "... src/tshirt.i"
	@echo "... src/tshirt.s"
	@echo "... src/underwear.o"
	@echo "... src/underwear.i"
	@echo "... src/underwear.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

